baseURL = "http://lomorage.com/"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "lomorage"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-138235951-1"

title = "Lomorage"
theme = "evie-hugo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
    [languages.en]

    [languages.en.menu]

    # Main menu

    [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url  = "/"
        weight = 1

#    [[languages.en.menu.main]]
#        identifier = "buy"
#        name = "Buy"
#        url  = "/buy/"
#        weight = 2

    [[languages.en.menu.main]]
        identifier = "installation"
        name = "Download Now"
        url  = "https://docs.lomorage.com/docs/Installation/"
        weight = 3

    [[languages.en.menu.main]]
        identifier = "survey"
        name = "Survey"
        url  = "/survey/"
        weight = 4

    [[languages.en.menu.main]]
        identifier = "faq"
        name = "FAQ"
        url  = "/faq/"
        weight = 5

    [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url  = "/blog/"
        weight = 6

    [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url  = "/contact/"
        weight = 7

    [languages.zh]
        [languages.zh.menu]

        # Main menu

        [[languages.zh.menu.main]]
            identifier = "home"
            name = "主页"
            url  = "/zh"
            weight = 1

#        [[languages.zh.menu.main]]
#            identifier = "buy"
#            name = "购买"
#            url  = "/zh/buy/"
#            weight = 2

        [[languages.zh.menu.main]]
            identifier = "installation"
            name = "立即下载"
            url  = "https://lomosw.lomorage.com/zh/index.html"
            weight = 3

        [[languages.zh.menu.main]]
            identifier = "survey"
            name = "调查问卷"
            url  = "/zh/survey/"
            weight = 4

        [[languages.zh.menu.main]]
            identifier = "faq"
            name = "常见问题"
            url  = "/zh/faq/"
            weight = 5

        [[languages.zh.menu.main]]
            identifier = "blog"
            name = "博客"
            url  = "/zh/blog/"
            weight = 6

        [[languages.zh.menu.main]]
            identifier = "contact"
            name = "联系"
            url  = "/zh/contact/"
            weight = 7

[params]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "lomorage@gmail.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

[params.footer]
    firstcolumn = ["<a href=\"https://github.com/lomorage/homepage\" target=\"_blank\" style=\"opacity: 1;\"><i class='fab fa-2x fa-github'></i></a>"]
    secondcolumn = ["<a href=\"https://join.slack.com/t/lomorage/shared_invite/enQtODc4MTE5ODQzNzkyLTRlY2U4MTQ1YjczYjBhMDcwMmExYTUxNTg2NTE5YmRkZjg2ZWQwZjg1MjEwMjQzZWVjMmEwZjk3ZGIyODY4ODM\" target=\"_blank\" style=\"opacity: 1;\"><i class='fab fa-2x fa-slack'></i></a>"]
    thirdcolumn = ["<a href=\"mailto:support@lomorage.com\" target=\"_blank\" style=\"opacity: 1;\"><i class='fa fa-2x fa-envelope'></i></a>"]


[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"
